app = 'acorn'
primary_region = 'syd'

[build]

[[services]]
  protocol = 'tcp'
  internal_port = 25575
  auto_stop_machines = 'stop'
  auto_start_machines = true

  [[services.ports]]
    port = 25575

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
